### ISSUE TITLE
drop the constructors to avoid double binding

### ISSUE THREAD

**Issue by vitormalencar** [gurgelrenan/todo_react#1]
https://github.com/gurgelrenan/todo_react/blob/83ba545e74a34cc8184945b95ed93fef3ebf21f5/src/App.js#L8

you could drop the constructor function to and use arrow functions instead

https://codeburst.io/how-to-not-react-common-anti-patterns-and-gotchas-in-react-40141fe0dcd

**Comment by gurgelrenan** [comment]
Fiz!
